import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
  },
  fullContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontSize: 20,
    color: '#333',
  },
  calendarContainer: {
    alignItems: 'center',
    width: '100%',
    height: '100%',
    marginTop: 140,
    padding: 0,
    borderWidth: 1,
    borderColor: '#000000',
  },
  calendarInnerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  calendarLeftButton: {
    margin: 5,
    width: 30,
    height: 30,
    textAlign: 'center',
    color: '#00FFFF',
    lineHeight: 30,
    fontSize: 20,
  },
  calendarRightButton: {
    margin: 5,
    width: 30,
    height: 30,
    textAlign: 'center',
    color: '#00FFFF',
    lineHeight: 30,
    fontSize: 20,
  },
  calendarDay: {
    width: 40,
    height: 40,
    margin: 5,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    lineHeight: 50,
    fontSize: 18,
  },
});